// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtopxuadayufyaxvglqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10b3B4dWFkYXl1ZnlheHZnbHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzIxODUsImV4cCI6MjA3Mzg0ODE4NX0.DcO_nIyjU36H_GZ3fkmOB1nKxybx2YD2KoIxrraQHEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});